### ISSUE TITLE
Setup MongoDB for the GraphQL Server

### ISSUE THREAD

**Issue by pavankpdev** [DuolearnHQ/ArtPlace#12]
The GraphQL server needs to be configured to work with a MongoDB database. This issue will involve setting up a connection to the database. 

Acceptance Criteria 
- Setup mongodb connection with the help of mongoose library
- Use ENVs to securely store the connection URI 
- create a `database` directory under `src` to store the connection file

**Comment by RwandaGloria** [comment]
Hi pavan! I am greatly interested in working to set this up. I believe this is within my capabilities, although I do not have any experience with GraphQL I am willing to learn 100%. I would appreciate it If you consider me thank you.

**Comment by pavankpdev** [comment]
Hi @RwandaGloria can update the status on this task please

**Comment by RwandaGloria** [comment]
Hi pavan. Yes I would. I'm having issues with the .env file. I would update soon please.

**Comment by pavankpdev** [comment]
Hey @RwandaGloria can you update the status on this issue please

**Comment by RwandaGloria** [comment]
Sorry for the delay. Let me do so.

**Comment by RwandaGloria** [comment]
Hi Pavan, I have updated and changed the files according to the reviews.
Please check. Thank you for your patience.
