### ISSUE TITLE
Create an ERC20 token for $ARTP

### ISSUE THREAD

**Issue by pavankpdev** [DuolearnHQ/ArtPlace#17]
We need to create an ERC20 token named $ARTP, which will be used as the primary currency for purchasing NFTs in our marketplace. The ERC20 token should be compatible with the Polygon network and follow the ERC20 standard.

Name: ArtPlace Token
Symbol: ARTP

We require the following functionality to be included in the ERC20 token:
- A total supply of 10 million tokens
- Decimals should be set to 18
- Token minting functionality should be enabled
- Token burning functionality should be enabled
- Access to the smart contract should be controlled via an admin address

Acceptance Criteria 
1. Contract should follow ERC20 standard from Openzeppelin
2. Contract should have mint and burn functions restricted to onlyOwner
3. Contract should have test cases written for all the possible use cases 
4. A flattened contract should be created and stored in `flattened` directory 
5. Contracts should be build with Solidity version 8 and above

Docs/Resources 
[Hardhat](https://hardhat.org/docs)
[Openzeppelin ERC20](https://docs.openzeppelin.com/contracts/4.x/erc20)

**Comment by ri-dev-git** [comment]
Can you assign me this issue?

**Comment by pavankpdev** [comment]
Hey @ri-dev-git, you're assigned to this task. Please review the ReadMe carefully before starting. The deadline for completion is Wednesday, May 10th.

Best of luck! Feel free to reach out to us on Discord if you need any assistance.

**Comment by ri-dev-git** [comment]
also should i add .env.example file to the contract dir?

**Comment by pavankpdev** [comment]
Oh I thought I pushed it, let me push the `.example.env` you can take pull @ri-dev-git

**Comment by pavankpdev** [comment]
It is added, you can take pull

**Comment by ri-dev-git** [comment]
Hi @pavankpdev! Should i be writing deploy and verify scripts?

**Comment by pavan38kp** [comment]
Yes @ri-dev-git

**Comment by ri-dev-git** [comment]
Hey @pavankpdev! i have updated the branch name and Fix some changes made to the contract and test! 

Here's the contract for review:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract ARTPToken is ERC20, ERC20Burnable, Ownable {
        constructor() ERC20("ArtPlace Token", "ARTP") {
        _mint(msg.sender, 10000000 * 10 ** decimals());
    }


    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }

    function burn(uint256 amount) public onlyOwner override{
        _burn(msg.sender,amount);
    }
}

```

You can clone the error we discussed earlier by `npx hardhat verify --network mumbai`.

**Comment by pavankpdev** [comment]
Hey @ri-dev-git I'm not sure what was the issue here, I was able to verify 
![image](https://github.com/DuolearnHQ/ArtPlace/assets/52795191/6abb6d98-8ad5-4be3-bd53-cdbbddf500a4)

**Comment by ri-dev-git** [comment]
Great!!! Are the contract and scripts good or require some change?

**Comment by pavankpdev** [comment]
@ri-dev-git Check PR, I've shared my reviews
