### ISSUE TITLE
Build User Context to store and manage User state globaly

### ISSUE THREAD

**Issue by pavankpdev** [DuolearnHQ/ArtPlace#20]
We aim to implement a User Context in the React project to store and manage the User state globally. This will provide a centralised approach for accessing and updating user-related data throughout the application.

User data structure 
1. fullname
2. email
3. wallet address
4. avatar

**Acceptance Criteria:**

1. Store the above specified user data in the User Context.
2. Create a User Context using React's Context API.
3. Implement the necessary functions or methods to update the User state in the User Context.
4. Integrate the User Context into relevant components to access and update the User state.
5. Export `useUser` hook that basically is a wrapper around this context. 
6. Test the functionality of the User Context to ensure proper global state management.

**Additional Guidelines:**

- Follow best practices for state management and ensure that sensitive user data is handled securely.
- Document any important decisions or considerations made during the implementation process.
- Write clear and concise code comments to improve code maintainability and readability.
- Test the User Context thoroughly to ensure it functions as expected and handles edge cases appropriately.

**Docs**
[Learn about context here](https://kentcdodds.com/blog/how-to-use-react-context-effectively)
[Official ReactJS docs on context](https://react.dev/learn/passing-data-deeply-with-context)

**Comment by Shaju06** [comment]
Hello, if no one is working, can i?

**Comment by pavankpdev** [comment]
Hey @ciradu2204 sure, you can take this up. 
This is a quick task, and deadline for this task would be 12th May

**Comment by ciradu2204** [comment]
Thank you. I am working on it.
