### ISSUE TITLE
Configuring React-Query and GraphQL CodeGen for Frontend

### ISSUE THREAD

**Issue by pavankpdev** [DuolearnHQ/ArtPlace#25]
Currently, our frontend application lacks a streamlined setup for managing GQL queries and generating type-safe code based on our GraphQL schema. To improve the efficiency and maintainability of our codebase, we need to configure React-Query and GraphQL CodeGen for frontend GQL queries.

**Objective**:
The objective of this issue is to set up React-Query and integrate GraphQL CodeGen into our frontend project. By doing so, we aim to achieve the following benefits:

Efficient Query Management: React-Query provides a powerful solution for managing GQL queries, caching, and data synchronization. Implementing React-Query will optimize our query handling, reduce unnecessary network requests, and enhance the overall performance of our application.

Type-Safe Code Generation: Integrating GraphQL CodeGen will allow us to automatically generate TypeScript types based on our GraphQL schema. This will enable compile-time type checking, improve code reliability, and provide better developer experience while working with GQL queries.

**Tasks**:

- Research React-Query and GraphQL CodeGen to understand their features, advantages, and suitability for our project.
- Install and configure React-Query in our frontend project, ensuring compatibility with our existing stack.
- Integrate GraphQL CodeGen as a `package.json` script to automatically generate TypeScript types based on our GraphQL schema.
- Test the implementation thoroughly, ensuring that React-Query functions as expected and that GraphQL CodeGen generates - accurate and up-to-date TypeScript types.
- Document the setup process and provide clear instructions for other team members to follow.

**Additional Information:**

Our frontend project is built with React.
- We are utilizing a GraphQL API as the backend for our application.
- **The GraphQL schema is not yet available as it's in WIP, you use any other public GraphQL server for testing the integration**. 
- The goal is to enhance query management, optimize performance, and ensure type safety in our frontend GQL queries.

Docs
[React-Query](https://tanstack.com/query/v4/docs/react/graphql)
[GQL CodeGen](https://the-guild.dev/graphql/codegen)
[A Blog on how to setup](https://codevoweb.com/nextjs-full-stack-app-with-react-query-and-graphql-codegen/)

**Comment by pavankpdev** [comment]
Hey @Shaju06 would you be interested to take this up?

**Comment by Shaju06** [comment]
Sure @pavankpdev just to confirm I've to setup graphql with react query on frontend and since scheme not available. I can use any dummy scheme to test integration right?

**Comment by pavan38kp** [comment]
Correct, you have to setup GraphQL client on frontend with react Query integration. In addition to that, you need to setup codegen that takes the schema as input and generates types and also hooks to make the query or mutation

**Comment by Shaju06** [comment]
okay sure, can you assigne me?

**Comment by Shaju06** [comment]
@pavan38kp please review
