### ISSUE TITLE
Setup Chakra UI and Configure the theme to align with the ArtPlace Design System

### ISSUE THREAD

**Issue by pavankpdev** [DuolearnHQ/ArtPlace#3]
As a part of integrating the ArtPlace Design System into our project, we need to set up Chakra UI and configure the theme to align with the ArtPlace Design System. 

Figma Designs
[Click here](https://www.figma.com/file/OOHh0fH24LVqaXy7cY1ULO/DE---NFT-Market-Place?node-id=0%3A1&t=Z1vX6qIIPzi5lRTr-1)

Acceptance Criteria
1. Install and set up Chakra UI in the project
2. Configure the Chakra UI theme to align with the ArtPlace Design System
3. Test the Chakra UI components and make sure they are styled correctly according to the ArtPlace Design System guidelines.

Once this issue is completed, the project will have a consistent look and feel based on the ArtPlace Design System guidelines.

**Comment by snehab162004** [comment]
Hey, I'm interested to solve this issue because I'm familiar with react I'm not aware of Chakra UI so I wish to learn new concept and I need to explore new things so can you assign this task to me ! !
